export default [
  {
    title: "Population Zero",
    slug: "https://source.unsplash.com/user/willianjusten/300x140",
    developer: "Rockstar Games",
    img: "https://source.unsplash.com/user/willianjusten/300x140",
    price: 235,
    promotionalPrice: 215,
  },
  {
    title: "Population Zero",
    slug: "https://source.unsplash.com/user/willianjusten/300x141",
    developer: "Rockstar Games",
    img: "https://source.unsplash.com/user/willianjusten/300x141",
    price: 235,
    promotionalPrice: 215,
  },
  {
    title: "Population Zero",
    slug: "https://source.unsplash.com/user/willianjusten/300x142",
    developer: "Rockstar Games",
    img: "https://source.unsplash.com/user/willianjusten/300x142",
    price: 235,
    promotionalPrice: 215,
  },
  {
    title: "Population Zero",
    slug: "https://source.unsplash.com/user/willianjusten/300x143",
    developer: "Rockstar Games",
    img: "https://source.unsplash.com/user/willianjusten/300x143",
    price: 235,
    promotionalPrice: 215,
  },
  {
    title: "Population Zero",
    slug: "https://source.unsplash.com/user/willianjusten/300x144",
    developer: "Rockstar Games",
    img: "https://source.unsplash.com/user/willianjusten/300x144",
    price: 235,
    promotionalPrice: 215,
  },
  {
    title: "Population Zero",
    slug: "https://source.unsplash.com/user/willianjusten/300x145",
    developer: "Rockstar Games",
    img: "https://source.unsplash.com/user/willianjusten/300x145",
    price: 235,
    promotionalPrice: 215,
  },
];
